"""Tests for the /generate-tests route (task 1.6).

Uses the FakeLlmClient + InMemoryArtifactStore so no API keys or S3 needed.
Verifies: returns s3_key/s3_url, test_count > 0, artifact is downloadable.
"""
from __future__ import annotations

from support import service_client

from app.main import app

client = service_client(app)


def test_generate_tests_returns_s3_url_and_count() -> None:
    response = client.post(
        "/generate-tests",
        json={
            "contract_id": "AC-GEN1",
            "title": "Fintech Dashboard",
            "requirements": "React dashboard with real-time charts, Node.js backend, PostgreSQL.",
        },
    )
    assert response.status_code == 200
    body = response.json()
    assert body["contract_id"] == "AC-GEN1"
    assert body["s3_key"].startswith("contracts/AC-GEN1/")
    assert body["s3_key"].endswith("/tests.js")
    assert body["framework"] == "jest"
    assert body["test_count"] >= 1
    assert body["generated_at"] != ""


def test_generate_tests_artifact_is_downloadable() -> None:
    gen = client.post(
        "/generate-tests",
        json={
            "contract_id": "AC-GEN2",
            "title": "ML API",
            "requirements": "Python FastAPI microservice for inference.",
        },
    )
    assert gen.status_code == 200
    gen.json()["s3_key"]

    # Download from the in-memory store via a separate route or directly.
    # The fake store URL is "in-memory://key" — we can't fetch that via HTTP.
    # Instead verify via /rag/count (same store pattern) or check via the store directly.
    # Here we verify the LLM fixture content was generated by checking test_count.
    assert gen.json()["test_count"] >= 3  # Fake fixture has 3 it() blocks.


def test_generate_tests_cypress_framework() -> None:
    response = client.post(
        "/generate-tests",
        json={
            "contract_id": "AC-GEN3",
            "title": "E2E Suite",
            "requirements": "Cypress end-to-end tests for the checkout flow.",
            "framework": "cypress",
        },
    )
    assert response.status_code == 200
    assert response.json()["framework"] == "cypress"
    assert "/cypress/" in response.json()["s3_key"]


def test_generate_tests_rejects_empty_requirements() -> None:
    response = client.post(
        "/generate-tests",
        json={
            "contract_id": "AC-GEN4",
            "title": "Empty",
            "requirements": "",
        },
    )
    assert response.status_code == 422


def test_generate_tests_rejects_invalid_framework() -> None:
    response = client.post(
        "/generate-tests",
        json={
            "contract_id": "AC-GEN5",
            "title": "Bad",
            "requirements": "Some requirements.",
            "framework": "mocha",
        },
    )
    assert response.status_code == 422


def test_generate_tests_returns_503_when_llm_unavailable() -> None:
    response = client.post(
        "/generate-tests",
        json={
            "contract_id": "AC-GEN6",
            "title": "503 Trigger Test",
            "requirements": "trigger-503 test scenario",
        },
    )
    assert response.status_code == 503
    assert response.headers.get("retry-after") == "5"
    assert "unavailable" in response.json()["detail"].lower() or "overloaded" in response.json()["detail"].lower()


def test_strip_code_fences_removes_markdown_wrapper() -> None:
    """The defect that made every stored bundle unloadable JavaScript."""
    from app.routes.test_gen import strip_code_fences

    raw = (
        "```javascript\n"
        "const { it } = require('@jest/globals');\n"
        "it('works', () => {});\n"
        "```\n\n"
        "Note: these tests assume the API is implemented."
    )
    out = strip_code_fences(raw)
    assert "```" not in out
    assert "Note:" not in out
    assert out.startswith("const {")
    assert out.endswith("it('works', () => {});")


def test_strip_code_fences_passes_through_unfenced_code() -> None:
    from app.routes.test_gen import strip_code_fences

    raw = "it('already bare', () => {});"
    assert strip_code_fences(raw) == raw


def test_strip_code_fences_keeps_every_block() -> None:
    from app.routes.test_gen import strip_code_fences

    raw = "```js\nit('a', () => {});\n```\ntext\n```js\nit('b', () => {});\n```"
    out = strip_code_fences(raw)
    assert "it('a'" in out and "it('b'" in out
    assert "text" not in out


def test_count_test_cases_ignores_words_ending_in_it() -> None:
    """`it(` as a substring also matches submit(, init(, wait(, exit(."""
    from app.routes.test_gen import count_test_cases

    code = """
    submit(form);
    init();
    await wait(100);
    process.exit(1);
    it('a real case', () => {});
    it.only('another', () => {});
    test('a third', () => {});
    """
    assert count_test_cases(code) == 3


def test_generated_bundle_is_loadable_javascript() -> None:
    """End to end: what /generate-tests stores must not be markdown."""
    gen = client.post(
        "/generate-tests",
        json={
            "contract_id": "AC-FENCE",
            "title": "Fence Check",
            "requirements": "A service with three endpoints.",
        },
    )
    assert gen.status_code == 200

    fetched = client.get("/generate-tests/AC-FENCE")
    assert fetched.status_code == 200
    assert not fetched.text.lstrip().startswith("```")
    assert "```" not in fetched.text


def test_fetch_generated_tests_404_when_never_generated() -> None:
    resp = client.get("/generate-tests/AC-NEVER-GENERATED")
    assert resp.status_code == 404
    assert "generate-tests" in resp.json()["detail"]


def test_local_file_artifact_store(tmp_path) -> None:
    from app.ports.artifact_store import LocalFileArtifactStore

    fallback_dir = str(tmp_path / "fallback")
    store = LocalFileArtifactStore(fallback_dir=fallback_dir)

    key = "contracts/AC-TEST/tests.js"
    body = "// test content"
    url = store.upload(key, body)

    assert url.startswith("file://")
    assert store.exists(key) is True
    assert store.download(key) == body

