"""LLM client port: call a generative model and return structured text.

Two adapters:
  - GeminiClient: calls Google's Gemini API via httpx
  - OpenAIClient: calls OpenAI ChatCompletions API via httpx
  - FakeLlmClient: returns a deterministic fixture for tests/offline

All adapters implement the same simple protocol: `generate(prompt, max_tokens) -> str`.
"""
from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class LlmClient(Protocol):
    """Minimal LLM interface — prompt in, text out."""

    def generate(self, prompt: str, max_tokens: int = 2048) -> str:
        ...


class LlmUnavailableError(Exception):
    """Raised when LLM provider is overloaded or unavailable."""

    def __init__(self, message: str = "LLM service is currently unavailable", retry_after: int = 5) -> None:
        super().__init__(message)
        self.message = message
        self.retry_after = retry_after


class FakeLlmClient:
    """Deterministic fake that returns a hardcoded Jest test file.

    The fixture contains realistic test assertions so downstream validation
    (S3 upload, file structure) can be exercised without a real API key.
    """

    _FIXTURE_TEST = '''\
/**
 * Auto-generated tests for contract {contract_id}.
 * Generated by AssureCode AI service — LLM test generator.
 */
const {{ describe, it, expect }} = require("@jest/globals");

describe("{contract_id}", () => {{
  it("should have a valid module export", () => {{
    // Placeholder — real tests generated by LLM
    expect(true).toBe(true);
  }});

  it("should pass basic smoke test", () => {{
    const result = 1 + 1;
    expect(result).toBe(2);
  }});

  it("should handle empty input gracefully", () => {{
    const fn = (input) => input ?? "default";
    expect(fn(null)).toBe("default");
    expect(fn("hello")).toBe("hello");
  }});
}});
'''

    def generate(self, prompt: str, max_tokens: int = 2048) -> str:
        import os
        if os.getenv("LLM_UNAVAILABLE") == "true" or "trigger-503" in prompt or "simulate_503" in prompt:
            raise LlmUnavailableError("LLM provider overloaded or unavailable", retry_after=5)

        # Extract contract_id from the prompt if present, otherwise use placeholder.
        contract_id = "UNKNOWN"
        for line in prompt.split("\n"):
            if "contract" in line.lower() and ("AC-" in line or "id" in line.lower()):
                for token in line.split():
                    if token.startswith("AC-"):
                        contract_id = token.strip().rstrip(".,;")
                        break
        return self._FIXTURE_TEST.format(contract_id=contract_id)


class GeminiClient:
    """Real adapter for Google Gemini API (generative language).

    Requires GEMINI_API_KEY env var. Falls back to FakeLlmClient on missing
    key or network error so the service still boots.
    """

    def __init__(self, api_key: str, model: str = "gemini-2.0-flash") -> None:
        self._api_key = api_key
        self._model = model

    def generate(self, prompt: str, max_tokens: int = 2048) -> str:
        """Call Gemini, or raise. See CloudflareWorkersAiClient.generate on why
        there is no FakeLlmClient fallback here."""
        import httpx

        if not self._api_key:
            raise LlmUnavailableError(
                "Gemini is not configured: set GEMINI_API_KEY, or set "
                "LLM_PROVIDER=fake for offline runs."
            )

        url = (
            f"https://generativelanguage.googleapis.com/v1beta/models/"
            f"{self._model}:generateContent?key={self._api_key}"
        )
        try:  # pragma: no cover — live API only
            resp = httpx.post(
                url,
                json={
                    "contents": [{"parts": [{"text": prompt}]}],
                    "generationConfig": {"maxOutputTokens": max_tokens},
                },
                timeout=30.0,
            )
        except httpx.HTTPError as err:
            raise LlmUnavailableError(f"Gemini request failed: {err}") from err

        if resp.status_code != 200:
            raise LlmUnavailableError(f"Gemini returned HTTP {resp.status_code}: {resp.text[:300]}")

        try:
            return resp.json()["candidates"][0]["content"]["parts"][0]["text"]
        except (ValueError, KeyError, IndexError) as err:
            raise LlmUnavailableError(f"Gemini returned an unexpected body: {resp.text[:300]}") from err


class OpenAIClient:
    """Real adapter for OpenAI ChatCompletions API.

    Requires OPENAI_API_KEY env var.
    """

    def __init__(self, api_key: str, model: str = "gpt-4o-mini") -> None:
        self._api_key = api_key
        self._model = model

    def generate(self, prompt: str, max_tokens: int = 2048) -> str:
        """Call OpenAI, or raise. See CloudflareWorkersAiClient.generate on why
        there is no FakeLlmClient fallback here."""
        import httpx

        if not self._api_key:
            raise LlmUnavailableError(
                "OpenAI is not configured: set OPENAI_API_KEY, or set "
                "LLM_PROVIDER=fake for offline runs."
            )

        try:  # pragma: no cover — live API only
            resp = httpx.post(
                "https://api.openai.com/v1/chat/completions",
                headers={"Authorization": f"Bearer {self._api_key}"},
                json={
                    "model": self._model,
                    "messages": [
                        {
                            "role": "system",
                            "content": "You are a test generation assistant. Output only valid JavaScript/TypeScript test code.",
                        },
                        {"role": "user", "content": prompt},
                    ],
                    "max_tokens": max_tokens,
                    "temperature": 0.3,
                },
                timeout=30.0,
            )
        except httpx.HTTPError as err:
            raise LlmUnavailableError(f"OpenAI request failed: {err}") from err

        if resp.status_code != 200:
            raise LlmUnavailableError(f"OpenAI returned HTTP {resp.status_code}: {resp.text[:300]}")

        try:
            return resp.json()["choices"][0]["message"]["content"]
        except (ValueError, KeyError, IndexError) as err:
            raise LlmUnavailableError(f"OpenAI returned an unexpected body: {resp.text[:300]}") from err


class CloudflareWorkersAiClient:
    """Real adapter for Cloudflare Workers AI API.

    Model endpoint: https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/run/{model}
    Requires CLOUDFLARE_ACCOUNT_ID and CLOUDFLARE_API_TOKEN env vars.
    """

    def __init__(
        self,
        account_id: str,
        api_token: str,
        model: str = "@cf/meta/llama-3.1-8b-instruct",
    ) -> None:
        self._account_id = account_id
        self._api_token = api_token
        self._model = model

    def generate(self, prompt: str, max_tokens: int = 2048) -> str:
        """Call Workers AI, or raise.

        This deliberately has no FakeLlmClient fallback. It used to answer every
        failure — missing credentials, network error, HTTP 4xx/5xx, unexpected
        response shape — by returning FakeLlmClient's hardcoded Jest fixture.
        Callers could not tell a real model response from a canned string, so a
        revoked API token would have quietly turned every security scan into a
        fixture that reports whatever the fixture says. Failures are now visible
        and routes translate them into HTTP 503.
        """
        import httpx

        if not self._account_id or not self._api_token:
            raise LlmUnavailableError(
                "Cloudflare Workers AI is not configured: set CLOUDFLARE_ACCOUNT_ID "
                "and CLOUDFLARE_API_TOKEN, or set LLM_PROVIDER=fake for offline runs."
            )

        url = f"https://api.cloudflare.com/client/v4/accounts/{self._account_id}/ai/run/{self._model}"
        try:
            resp = httpx.post(
                url,
                headers={"Authorization": f"Bearer {self._api_token}"},
                json={
                    "messages": [
                        {
                            "role": "system",
                            "content": "You are AssureCode AI assistant for test generation, security scanning, and XAI score evaluation.",
                        },
                        {"role": "user", "content": prompt},
                    ],
                    "max_tokens": max_tokens,
                },
                timeout=30.0,
            )
        except httpx.HTTPError as err:
            raise LlmUnavailableError(f"Cloudflare Workers AI request failed: {err}") from err

        if resp.status_code != 200:
            detail = resp.text[:300]
            raise LlmUnavailableError(
                f"Cloudflare Workers AI returned HTTP {resp.status_code}: {detail}"
            )

        try:
            data = resp.json()
        except ValueError as err:
            raise LlmUnavailableError("Cloudflare Workers AI returned a non-JSON body") from err

        # Workers AI answers in two shapes depending on the model and account:
        # the flat {"result": {"response": "..."}} form, and an OpenAI-style
        # {"result": {"choices": [{"message": {"content": "..."}}]}}. Both are
        # live in production, so accept either rather than treating the second
        # as a failure — which is what happened to every scan in the OWASP
        # harness until this was found.
        result = data.get("result") or {}

        response = result.get("response")
        if isinstance(response, str) and response != "":
            return response

        choices = result.get("choices")
        if isinstance(choices, list) and choices:
            content = (choices[0] or {}).get("message", {}).get("content")
            if isinstance(content, str) and content != "":
                return content

        raise LlmUnavailableError(
            f"Cloudflare Workers AI returned no usable response field: {str(data)[:300]}"
        )

