"""LLM client port: call a generative model and return structured text.

Two adapters:
  - CloudflareWorkersAiClient: calls Cloudflare Workers AI via httpx
  - FakeLlmClient: returns a deterministic fixture for tests/offline

Both implement the same simple protocol: `generate(prompt, max_tokens) -> str`.

Cloudflare Workers AI is the only provider. Gemini and OpenAI adapters used to
live here as well, selected by LLM_PROVIDER, and were removed: three code paths
for one capability meant three sets of credentials to hold, three response
shapes to keep parsing, and two providers that nothing in any environment was
configured to use. A provider seam that is never exercised is not portability,
it is untested code on the critical path of test generation and the security
scan's second layer.

Adding a provider back means writing one class with a `generate` method and
returning it from `get_llm_client()` in app/deps.py — the port is the seam, and
it is unchanged.
"""
from __future__ import annotations

from datetime import UTC, datetime
from email.utils import parsedate_to_datetime
from typing import Protocol, runtime_checkable

#: Total attempts (1 original + retries) for a Cloudflare call that fails in a
#: way retrying can plausibly fix. Mirrors packages/razorpay-adapter's own
#: MAX_ATTEMPTS=3 — "how many times before giving up" is a property of this
#: codebase's retry policy, not of which outbound call happens to be involved.
_MAX_ATTEMPTS = 3
_INITIAL_BACKOFF_S = 0.5
#: Never wait longer than this for one retry, even if Retry-After asks for
#: more — a synchronous test-generation/security-scan call already has its
#: own 30s-per-attempt budget; a single stalled retry must not multiply that
#: unboundedly.
_MAX_BACKOFF_S = 8.0


def _parse_retry_after(header_value: str | None) -> float | None:
    """Seconds, or an HTTP-date (RFC 9110 permits either) -> seconds from now. None if absent/unparseable, so the caller falls back to its own exponential backoff rather than trusting a malformed header."""
    if not header_value:
        return None
    try:
        seconds = float(header_value)
        if seconds >= 0:
            return seconds
    except ValueError:
        pass
    try:
        dt = parsedate_to_datetime(header_value)
    except (TypeError, ValueError):
        return None
    if dt is None:
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=UTC)
    return max(0.0, (dt - datetime.now(UTC)).total_seconds())


@runtime_checkable
class LlmClient(Protocol):
    """Minimal LLM interface — prompt in, text out."""

    def generate(self, prompt: str, max_tokens: int = 2048) -> str:
        ...


class LlmUnavailableError(Exception):
    """Raised when LLM provider is overloaded or unavailable."""

    def __init__(self, message: str = "LLM service is currently unavailable", retry_after: int = 5) -> None:
        super().__init__(message)
        self.message = message
        self.retry_after = retry_after


class FakeLlmClient:
    """Deterministic fake that returns a hardcoded Jest test file.

    The fixture contains realistic test assertions so downstream validation
    (S3 upload, file structure) can be exercised without a real API key.
    """

    _FIXTURE_TEST = '''\
/**
 * Auto-generated tests for contract {contract_id}.
 * Generated by AssureCode AI service — LLM test generator.
 */
const {{ describe, it, expect }} = require("@jest/globals");

describe("{contract_id}", () => {{
  it("should have a valid module export", () => {{
    // Placeholder — real tests generated by LLM
    expect(true).toBe(true);
  }});

  it("should pass basic smoke test", () => {{
    const result = 1 + 1;
    expect(result).toBe(2);
  }});

  it("should handle empty input gracefully", () => {{
    const fn = (input) => input ?? "default";
    expect(fn(null)).toBe("default");
    expect(fn("hello")).toBe("hello");
  }});
}});
'''

    #: What the OWASP Layer 2 scan asks for: a JSON array of findings.
    #:
    #: Empty, and that is the honest answer. This fake has no detection logic,
    #: so the only report it can truthfully return is "I found nothing" — which
    #: still exercises the parse-and-merge path in routes/security_scan.py and
    #: still lets `layersRun` include "llm".
    _FIXTURE_SECURITY_REPORT = "[]"

    def generate(self, prompt: str, max_tokens: int = 2048) -> str:
        import os
        if os.getenv("LLM_UNAVAILABLE") == "true" or "trigger-503" in prompt or "simulate_503" in prompt:
            raise LlmUnavailableError("LLM provider overloaded or unavailable", retry_after=5)

        # The security scan and the test generator share one `generate` method,
        # so the fake has to tell them apart from the prompt.
        #
        # It did not, and returned a Jest fixture for both. The scanner then
        # failed to parse a test file as a findings array and answered 502, so
        # ci-worker recorded `securityScanComplete: false`, the oracle read that
        # as `securityPassed: false`, and **no contract could settle in any
        # configuration without a live Cloudflare key** — including every
        # offline demo and the whole integration suite. The failure surfaced
        # three services away from its cause.
        if self._looks_like_a_security_scan(prompt):
            return self._FIXTURE_SECURITY_REPORT

        # Extract contract_id from the prompt if present, otherwise use placeholder.
        contract_id = "UNKNOWN"
        for line in prompt.split("\n"):
            if "contract" in line.lower() and ("AC-" in line or "id" in line.lower()):
                for token in line.split():
                    if token.startswith("AC-"):
                        contract_id = token.strip().rstrip(".,;")
                        break
        return self._FIXTURE_TEST.format(contract_id=contract_id)

    @staticmethod
    def _looks_like_a_security_scan(prompt: str) -> bool:
        """Distinguish the OWASP Layer 2 prompt from the test-generation one.

        Matched on two phrases from PROMPT_TEMPLATE in routes/security_scan.py
        that are load-bearing there — the reviewer role and the JSON-array
        instruction — rather than on one incidental word. Both must appear, so
        a contract whose requirements happen to mention "security" does not
        get an empty findings array instead of its tests.
        """
        lowered = prompt.lower()
        return "application security reviewer" in lowered and "json array" in lowered


class CloudflareWorkersAiClient:
    """Real adapter for Cloudflare Workers AI API.

    Model endpoint: https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/run/{model}
    Requires CLOUDFLARE_ACCOUNT_ID and CLOUDFLARE_API_TOKEN env vars.
    """

    def __init__(
        self,
        account_id: str,
        api_token: str,
        model: str = "@cf/meta/llama-3.1-8b-instruct",
    ) -> None:
        self._account_id = account_id
        self._api_token = api_token
        self._model = model

    def generate(self, prompt: str, max_tokens: int = 2048) -> str:
        """Call Workers AI, or raise.

        This deliberately has no FakeLlmClient fallback. It used to answer every
        failure — missing credentials, network error, HTTP 4xx/5xx, unexpected
        response shape — by returning FakeLlmClient's hardcoded Jest fixture.
        Callers could not tell a real model response from a canned string, so a
        revoked API token would have quietly turned every security scan into a
        fixture that reports whatever the fixture says. Failures are now visible
        and routes translate them into HTTP 503.
        """
        if not self._account_id or not self._api_token:
            raise LlmUnavailableError(
                "Cloudflare Workers AI is not configured: set CLOUDFLARE_ACCOUNT_ID "
                "and CLOUDFLARE_API_TOKEN, or set LLM_PROVIDER=fake for offline runs."
            )

        url = f"https://api.cloudflare.com/client/v4/accounts/{self._account_id}/ai/run/{self._model}"
        headers = {"Authorization": f"Bearer {self._api_token}"}
        payload = {
            "messages": [
                {
                    "role": "system",
                    "content": "You are AssureCode AI assistant for test generation, security scanning, and XAI score evaluation.",
                },
                {"role": "user", "content": prompt},
            ],
            "max_tokens": max_tokens,
        }

        resp = self._post_with_retry(url, headers, payload)

        try:
            data = resp.json()
        except ValueError as err:
            raise LlmUnavailableError("Cloudflare Workers AI returned a non-JSON body") from err

        # Workers AI answers in two shapes depending on the model and account:
        # the flat {"result": {"response": "..."}} form, and an OpenAI-style
        # {"result": {"choices": [{"message": {"content": "..."}}]}}. Both are
        # live in production, so accept either rather than treating the second
        # as a failure — which is what happened to every scan in the OWASP
        # harness until this was found.
        result = data.get("result") or {}

        response = result.get("response")
        if isinstance(response, str) and response != "":
            return response

        choices = result.get("choices")
        if isinstance(choices, list) and choices:
            content = (choices[0] or {}).get("message", {}).get("content")
            if isinstance(content, str) and content != "":
                return content

        raise LlmUnavailableError(
            f"Cloudflare Workers AI returned no usable response field: {str(data)[:300]}"
        )

    def _post_with_retry(self, url: str, headers: dict, payload: dict):
        """POST with retry, retrying only failures retrying can plausibly fix.

        A 429 (honouring Retry-After when Cloudflare sends one) or a 5xx or a
        network-level failure — a DNS failure, a dropped connection, the
        client-side timeout — is retried. Any other 4xx (bad request, a
        revoked token, an unknown model) is a real rejection: retrying it
        wastes a call without changing the outcome, and would also mean
        resending a prompt whose *first* attempt may already have been billed
        or logged server-side before the response was lost.
        """
        import time

        import httpx

        last_err: LlmUnavailableError | None = None
        for attempt in range(1, _MAX_ATTEMPTS + 1):
            try:
                resp = httpx.post(url, headers=headers, json=payload, timeout=30.0)
            except httpx.HTTPError as err:
                last_err = LlmUnavailableError(f"Cloudflare Workers AI request failed: {err}")
                if attempt == _MAX_ATTEMPTS:
                    raise last_err from err
                time.sleep(min(_MAX_BACKOFF_S, _INITIAL_BACKOFF_S * (2 ** (attempt - 1))))
                continue

            if resp.status_code == 200:
                return resp

            retryable = resp.status_code == 429 or resp.status_code >= 500
            detail = resp.text[:300]
            last_err = LlmUnavailableError(
                f"Cloudflare Workers AI returned HTTP {resp.status_code}: {detail}"
            )
            if not retryable or attempt == _MAX_ATTEMPTS:
                raise last_err

            retry_after = _parse_retry_after(resp.headers.get("retry-after")) if resp.status_code == 429 else None
            backoff = retry_after if retry_after is not None else _INITIAL_BACKOFF_S * (2 ** (attempt - 1))
            time.sleep(min(_MAX_BACKOFF_S, backoff))

        # Unreachable — every branch above returns or raises — but satisfies
        # static analysis without an unsound assertion that last_err is set.
        raise last_err or LlmUnavailableError("Cloudflare Workers AI request failed after retries")

