export const ESCROW_STATUSES = {
  UNFUNDED: 'UNFUNDED',
  HELD_IN_ESCROW: 'HELD_IN_ESCROW',
  RELEASE_PENDING: 'RELEASE_PENDING',
  SETTLED: 'SETTLED',
  DISPUTED: 'DISPUTED',
  REFUNDED: 'REFUNDED',
};

export const ORACLE_SIGNAL_TYPES = {
  CI_TESTS: 'CI_TESTS',
  SECURITY_SCAN: 'SECURITY_SCAN',
  SCOPE_RAG: 'SCOPE_RAG',
  XAI_SCORE: 'XAI_SCORE',
  LEDGER_INTEGRITY: 'LEDGER_INTEGRITY',
};

export const ORACLE_SIGNAL_STATUS = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  FAILED: 'FAILED',
  BYPASSED: 'BYPASSED',
};
